USE BURGER_DB;

INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('BACON CHEESE BURGER', FALSE);
INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('PLAIN JANE BURGER', TRUE);
INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('PINAPPLE BURGER', FALSE);

Select *
 FROM BURGERS;